# Generated by Django 4.2.16 on 2024-11-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='password',
            field=models.IntegerField(unique=True),
        ),
    ]
